// 出題語彙を「章」に分けて持つ。
//   日本語: { w: 表示, k: 読み }   ラテン文字圏: 文字列そのまま
//
// 章はテーマ（語彙 + 画面の色）を切り替えるための単位。5 ウェーブで 1 章、
// 章の最後がボスウェーブ。新しいシステムを足さずに「進んでいる感じ」を作るための仕掛け。
//
// 各章は 4〜16 打鍵の語をひと通り揃えること。高ウェーブでは長い語しか出題されないので、
// 短い語だけの章があると出題プールが枯れてテーマが崩れる。

export const CHAPTERS = [
  {
    id: 'wild',
    name: { en: 'THE WILD', ja: '野 生' },
    hue: 150,
    shape: 'leaf',
    motif: 'pollen',
    ja: [
      { w: '猫', k: 'ねこ' }, { w: '犬', k: 'いぬ' }, { w: '星', k: 'ほし' }, { w: '森', k: 'もり' },
      { w: '嵐', k: 'あらし' }, { w: '梟', k: 'ふくろう' }, { w: '海月', k: 'くらげ' }, { w: '蜻蛉', k: 'とんぼ' },
      { w: '百足', k: 'むかで' }, { w: '駱駝', k: 'らくだ' }, { w: '雷', k: 'かみなり' }, { w: '氷柱', k: 'つらら' },
      { w: '稲妻', k: 'いなずま' }, { w: '朝露', k: 'あさつゆ' }, { w: '雪崩', k: 'なだれ' }, { w: '津波', k: 'つなみ' },
      { w: '陽炎', k: 'かげろう' }, { w: '雷鳥', k: 'らいちょう' }, { w: '夜明け', k: 'よあけ' }, { w: '夕焼け', k: 'ゆうやけ' },
      { w: '真夜中', k: 'まよなか' }, { w: '蝸牛', k: 'かたつむり' }, { w: '木漏れ日', k: 'こもれび' }, { w: '蜃気楼', k: 'しんきろう' },
      { w: '天道虫', k: 'てんとうむし' }, { w: '深山幽谷', k: 'しんざんゆうこく' }, { w: '花鳥風月', k: 'かちょうふうげつ' },
      { w: '海千山千', k: 'うみせんやません' }, { w: '疾風迅雷', k: 'しっぷうじんらい' }, { w: '天変地異', k: 'てんぺんちい' },
      { w: '霧雨', k: 'きりさめ' }, { w: '銀世界', k: 'ぎんせかい' }, { w: '三日月', k: 'みかづき' },
      { w: '大自然', k: 'だいしぜん' }, { w: '渡り鳥', k: 'わたりどり' }, { w: '原生林', k: 'げんせいりん' },
      { w: '風光明媚', k: 'ふうこうめいび' }, { w: '春夏秋冬', k: 'しゅんかしゅうとう' },
      { w: '森林限界', k: 'しんりんげんかい' }, { w: '絶滅危惧種', k: 'ぜつめつきぐしゅ' },
      { w: '鷲', k: 'わし' }, { w: '狐', k: 'きつね' }, { w: '狼', k: 'おおかみ' }, { w: '鹿', k: 'しか' },
      { w: '蛍', k: 'ほたる' }, { w: '燕', k: 'つばめ' }, { w: '兎', k: 'うさぎ' }, { w: '栗鼠', k: 'りす' },
      { w: '苔', k: 'こけ' }, { w: '筍', k: 'たけのこ' }, { w: '土筆', k: 'つくし' }, { w: '薄氷', k: 'うすらい' },
      { w: '沼', k: 'ぬま' }, { w: '滝', k: 'たき' }, { w: '岬', k: 'みさき' }, { w: '洞窟', k: 'どうくつ' },
      { w: '砂丘', k: 'さきゅう' }, { w: '湿原', k: 'しつげん' }, { w: '氷河', k: 'ひょうが' }, { w: '潮騒', k: 'しおさい' },
      { w: '北風', k: 'きたかぜ' }, { w: '夕立', k: 'ゆうだち' }, { w: '霜柱', k: 'しもばしら' }, { w: '流氷', k: 'りゅうひょう' },
      { w: '虹', k: 'にじ' }, { w: '雲海', k: 'うんかい' }, { w: '極光', k: 'きょっこう' }, { w: '日食', k: 'にっしょく' },
      { w: '渓谷', k: 'けいこく' }, { w: '樹海', k: 'じゅかい' }, { w: '密林', k: 'みつりん' }, { w: '荒野', k: 'こうや' },
      { w: '野兎', k: 'のうさぎ' }, { w: '雷雲', k: 'らいうん' }, { w: '白樺', k: 'しらかば' }, { w: '群青', k: 'ぐんじょう' },
      { w: '大寒波', k: 'だいかんぱ' }, { w: '春一番', k: 'はるいちばん' }, { w: '五月晴れ', k: 'さつきばれ' },
      { w: '弱肉強食', k: 'じゃくにくきょうしょく' }, { w: '自然淘汰', k: 'しぜんとうた' },
      { w: '生態系', k: 'せいたいけい' }, { w: '光合成', k: 'こうごうせい' }, { w: '食物連鎖', k: 'しょくもつれんさ' },
    ],
    en: [
      'cat', 'owl', 'moth', 'crow', 'wolf', 'hare', 'toad', 'wasp', 'crane', 'viper',
      'storm', 'frost', 'ember', 'tide', 'dusk', 'dawn', 'haze', 'firefly', 'driftwood', 'starlight',
      'thunder', 'drizzle', 'blizzard', 'moonlight', 'undertow', 'wanderlust', 'afterglow',
      'thunderstorm', 'constellation', 'phosphorescent', 'weatherbeaten', 'thunderstruck',
      'riverbed', 'snowmelt', 'coldsnap', 'nightfall', 'windswept', 'hailstone', 'wolfsbane',
      'evergreen', 'waterfall', 'meadowlark', 'stormfront', 'thundercloud', 'undergrowth',
      'cinder', 'willow', 'bramble', 'thistle', 'gosling', 'heather', 'sapling',
      'thunderhead', 'stormbringer', 'precipitation',
      'fox', 'elk', 'lynx', 'boar', 'reed', 'fern', 'silt', 'dune', 'peat', 'kelp',
      'otter', 'raven', 'stork', 'adder', 'gorse', 'briar', 'shale', 'creek', 'ridge', 'grove',
      'marsh', 'thorn', 'birch', 'cedar', 'spruce', 'lichen', 'canyon', 'meadow', 'glacier', 'estuary',
      'sunfall', 'seafoam', 'wildfire', 'rainfall', 'snowdrift', 'windchill', 'treeline', 'foxglove',
      'saltmarsh', 'mudslide', 'quicksand', 'floodplain', 'permafrost', 'rainforest',
      'photosynthesis', 'biodiversity', 'wilderness', 'hibernation', 'migration',
    ],
  },
  {
    id: 'machine',
    name: { en: 'THE MACHINE', ja: '機 械 都 市' },
    hue: 205,
    shape: 'gear',
    motif: 'scan',
    ja: [
      { w: '電池', k: 'でんち' }, { w: '回路', k: 'かいろ' }, { w: '線路', k: 'せんろ' }, { w: '信号', k: 'しんごう' },
      { w: '歯車', k: 'はぐるま' }, { w: '発条', k: 'ぜんまい' }, { w: '砦', k: 'とりで' }, { w: '螺旋', k: 'らせん' },
      { w: '迷路', k: 'めいろ' }, { w: '硝子', k: 'がらす' }, { w: '灯台', k: 'とうだい' }, { w: '改札', k: 'かいさつ' },
      { w: '踏切', k: 'ふみきり' }, { w: '地下鉄', k: 'ちかてつ' }, { w: '機関車', k: 'きかんしゃ' }, { w: '飛行船', k: 'ひこうせん' },
      { w: '交差点', k: 'こうさてん' }, { w: '冷蔵庫', k: 'れいぞうこ' }, { w: '洗濯機', k: 'せんたくき' }, { w: '扇風機', k: 'せんぷうき' },
      { w: '掃除機', k: 'そうじき' }, { w: '図書館', k: 'としょかん' }, { w: '商店街', k: 'しょうてんがい' }, { w: '住宅街', k: 'じゅうたくがい' },
      { w: '博物館', k: 'はくぶつかん' }, { w: '美術館', k: 'びじゅつかん' }, { w: '確定申告', k: 'かくていしんこく' },
      { w: '取扱説明書', k: 'とりあつかいせつめいしょ' }, { w: '大量生産', k: 'たいりょうせいさん' }, { w: '機械仕掛け', k: 'きかいじかけ' },
      { w: '信号機', k: 'しんごうき' }, { w: '変電所', k: 'へんでんしょ' }, { w: '観覧車', k: 'かんらんしゃ' },
      { w: '高架橋', k: 'こうかきょう' }, { w: '発電所', k: 'はつでんしょ' }, { w: '操縦席', k: 'そうじゅうせき' },
      { w: '電気回路', k: 'でんきかいろ' }, { w: '自動改札', k: 'じどうかいさつ' },
      { w: '製造工程', k: 'せいぞうこうてい' }, { w: '無人運転', k: 'むじんうんてん' },
      { w: '機械学習', k: 'きかいがくしゅう' }, { w: '産業革命', k: 'さんぎょうかくめい' },
      { w: '螺子', k: 'ねじ' }, { w: '鋼', k: 'はがね' }, { w: '軸受', k: 'じくうけ' }, { w: '滑車', k: 'かっしゃ' },
      { w: '弁', k: 'べん' }, { w: '配管', k: 'はいかん' }, { w: '導線', k: 'どうせん' }, { w: '端子', k: 'たんし' },
      { w: '基板', k: 'きばん' }, { w: '筐体', k: 'きょうたい' }, { w: '溶接', k: 'ようせつ' }, { w: '鋳型', k: 'いがた' },
      { w: '旋盤', k: 'せんばん' }, { w: '工具', k: 'こうぐ' }, { w: '油圧', k: 'ゆあつ' }, { w: '軌道', k: 'きどう' },
      { w: '車輪', k: 'しゃりん' }, { w: '煙突', k: 'えんとつ' }, { w: '倉庫', k: 'そうこ' }, { w: '桟橋', k: 'さんばし' },
      { w: '水門', k: 'すいもん' }, { w: '鉄塔', k: 'てっとう' }, { w: '路面電車', k: 'ろめんでんしゃ' },
      { w: '自動販売機', k: 'じどうはんばいき' }, { w: '非常階段', k: 'ひじょうかいだん' },
      { w: '電光掲示板', k: 'でんこうけいじばん' }, { w: '換気扇', k: 'かんきせん' }, { w: '発条仕掛け', k: 'ぜんまいじかけ' },
      { w: '整備工場', k: 'せいびこうじょう' }, { w: '制御装置', k: 'せいぎょそうち' }, { w: '内燃機関', k: 'ないねんきかん' },
      { w: '蒸気機関', k: 'じょうききかん' }, { w: '送電線', k: 'そうでんせん' }, { w: '変圧器', k: 'へんあつき' },
      { w: '設計図', k: 'せっけいず' }, { w: '試作品', k: 'しさくひん' }, { w: '量産体制', k: 'りょうさんたいせい' },
      { w: '完全自動', k: 'かんぜんじどう' }, { w: '遠隔操作', k: 'えんかくそうさ' },
    ],
    en: [
      'bolt', 'gear', 'iron', 'coal', 'clay', 'valve', 'cable', 'anchor', 'rudder', 'mast',
      'engine', 'piston', 'boiler', 'turbine', 'conduit', 'gearbox', 'circuit', 'furnace',
      'terminal', 'registry', 'protocol', 'blueprint', 'clockwork', 'lighthouse', 'greenhouse',
      'counterweight', 'perpendicular', 'reconstruction', 'disintegration', 'lighthousekeeper',
      'flywheel', 'assembly', 'radiator', 'generator', 'condenser', 'mechanism', 'framework',
      'powerline', 'machinery', 'ironworks', 'crankshaft', 'switchgear', 'compressor', 'transistor',
      'transmission', 'manufacturing', 'infrastructure', 'servomechanism', 'reciprocating',
      'cog', 'rivet', 'screw', 'lever', 'crank', 'gauge', 'shaft', 'plate', 'wire', 'pulley',
      'girder', 'socket', 'nozzle', 'bearing', 'chassis', 'housing', 'coolant', 'exhaust',
      'reactor', 'foundry', 'smelter', 'derrick', 'catwalk', 'freight', 'railyard', 'scaffold',
      'toolshed', 'hydraulic', 'pneumatic', 'diagnostic', 'servomotor', 'flowmeter',
      'switchboard', 'transformer', 'accelerator', 'conveyorbelt', 'substation',
      'automation', 'calibration', 'engineering', 'installation', 'maintenance',
    ],
  },
  {
    id: 'observatory',
    name: { en: 'THE OBSERVATORY', ja: '観 測 所' },
    hue: 265,
    shape: 'tri',
    motif: 'constellation',
    ja: [
      { w: '仮説', k: 'かせつ' }, { w: '演算', k: 'えんざん' }, { w: '観測', k: 'かんそく' }, { w: '実験', k: 'じっけん' },
      { w: '銀河', k: 'ぎんが' }, { w: '境界', k: 'きょうかい' }, { w: '瞬間', k: 'しゅんかん' }, { w: '永遠', k: 'えいえん' },
      { w: '証明', k: 'しょうめい' }, { w: '奔流', k: 'ほんりゅう' }, { w: '静寂', k: 'せいじゃく' }, { w: '天文台', k: 'てんもんだい' },
      { w: '砂時計', k: 'すなどけい' }, { w: '羅針盤', k: 'らしんばん' }, { w: '万華鏡', k: 'まんげきょう' },
      { w: '走馬灯', k: 'そうまとう' }, { w: '一期一会', k: 'いちごいちえ' }, { w: '臨機応変', k: 'りんきおうへん' },
      { w: '試行錯誤', k: 'しこうさくご' }, { w: '電光石火', k: 'でんこうせっか' }, { w: '起死回生', k: 'きしかいせい' },
      { w: '前代未聞', k: 'ぜんだいみもん' }, { w: '因果応報', k: 'いんがおうほう' }, { w: '不可逆性', k: 'ふかぎゃくせい' },
      { w: '観測装置', k: 'かんそくそうち' }, { w: '相互作用', k: 'そうごさよう' }, { w: '量子力学', k: 'りょうしりきがく' },
      { w: '天体観測', k: 'てんたいかんそく' }, { w: '無限遠点', k: 'むげんえんてん' }, { w: '光年', k: 'こうねん' },
      { w: '軌跡', k: 'きせき' }, { w: '座標', k: 'ざひょう' }, { w: '振幅', k: 'しんぷく' }, { w: '周期', k: 'しゅうき' },
      { w: '波長', k: 'はちょう' }, { w: '屈折', k: 'くっせつ' }, { w: '干渉', k: 'かんしょう' }, { w: '回折', k: 'かいせつ' },
      { w: '真空', k: 'しんくう' }, { w: '重力', k: 'じゅうりょく' }, { w: '磁場', k: 'じば' }, { w: '素粒子', k: 'そりゅうし' },
      { w: '原子核', k: 'げんしかく' }, { w: '分光器', k: 'ぶんこうき' }, { w: '望遠鏡', k: 'ぼうえんきょう' },
      { w: '顕微鏡', k: 'けんびきょう' }, { w: '観測者', k: 'かんそくしゃ' }, { w: '標本', k: 'ひょうほん' },
      { w: '定理', k: 'ていり' }, { w: '公理', k: 'こうり' }, { w: '再現性', k: 'さいげんせい' },
      { w: '有意差', k: 'ゆういさ' }, { w: '誤差範囲', k: 'ごさはんい' }, { w: '対照実験', k: 'たいしょうじっけん' },
      { w: '恒星', k: 'こうせい' }, { w: '惑星', k: 'わくせい' }, { w: '彗星', k: 'すいせい' }, { w: '星雲', k: 'せいうん' },
      { w: '衛星軌道', k: 'えいせいきどう' }, { w: '天球儀', k: 'てんきゅうぎ' }, { w: '望遠観測', k: 'ぼうえんかんそく' },
      { w: '絶対零度', k: 'ぜったいれいど' }, { w: '熱力学', k: 'ねつりきがく' }, { w: '万有引力', k: 'ばんゆういんりょく' },
      { w: '観測限界', k: 'かんそくげんかい' }, { w: '理論物理', k: 'りろんぶつり' },
    ],
    en: [
      'atom', 'flux', 'prism', 'orbit', 'vector', 'photon', 'lens', 'signal', 'cipher', 'ledger',
      'gravity', 'entropy', 'quantum', 'spectrum', 'eclipse', 'parallax', 'friction', 'momentum',
      'anomaly', 'catalyst', 'synthesis', 'resonance', 'archive', 'calibrate', 'hypothesis',
      'equilibrium', 'circumference', 'interference', 'transmutation', 'incomprehensible',
      'telescope', 'astrolabe', 'starchart', 'longitude', 'magnitude', 'satellite', 'wavelength',
      'refraction', 'trajectory', 'luminosity', 'coordinate', 'diffraction', 'observatory',
      'astronomical', 'interstellar', 'spectroscopy', 'gravitational',
      'arc', 'axis', 'node', 'mass', 'ray', 'wave', 'field', 'probe', 'chart', 'scale',
      'comet', 'nebula', 'zenith', 'apogee', 'vacuum', 'isotope', 'neutron', 'plasma',
      'binary', 'lattice', 'inertia', 'density', 'tangent', 'radiant', 'sextant', 'almanac',
      'variance', 'aperture', 'redshift', 'starfield', 'telemetry', 'refractor',
      'oscillation', 'equinox', 'declination', 'observation', 'measurement',
      'astrophysics', 'cosmology', 'relativity', 'singularity', 'wavefunction',
    ],
  },
  {
    id: 'arcane',
    name: { en: 'THE ARCANE', ja: '呪 詛' },
    hue: 340,
    shape: 'spike',
    motif: 'embers',
    ja: [
      { w: '刃', k: 'やいば' }, { w: '塔', k: 'とう' }, { w: '盾', k: 'たて' }, { w: '鎧', k: 'よろい' },
      { w: '弓矢', k: 'ゆみや' }, { w: '呪文', k: 'じゅもん' }, { w: '魔法', k: 'まほう' }, { w: '結界', k: 'けっかい' },
      { w: '封印', k: 'ふういん' }, { w: '怪異', k: 'かいい' }, { w: '妖怪', k: 'ようかい' }, { w: '亡霊', k: 'ぼうれい' },
      { w: '地下牢', k: 'ちかろう' }, { w: '城壁', k: 'じょうへき' }, { w: '影法師', k: 'かげぼうし' },
      { w: '天邪鬼', k: 'あまのじゃく' }, { w: '油断大敵', k: 'ゆだんたいてき' }, { w: '悪霊退散', k: 'あくりょうたいさん' },
      { w: '一刀両断', k: 'いっとうりょうだん' }, { w: '空前絶後', k: 'くうぜんぜつご' }, { w: '呪術式', k: 'じゅじゅつしき' },
      { w: '禁忌', k: 'きんき' }, { w: '生贄', k: 'いけにえ' }, { w: '祟り', k: 'たたり' }, { w: '結晶', k: 'けっしょう' },
      { w: '深淵', k: 'しんえん' }, { w: '幽玄', k: 'ゆうげん' }, { w: '百鬼夜行', k: 'ひゃっきやこう' },
      { w: '因縁', k: 'いんねん' }, { w: '不死鳥', k: 'ふしちょう' },
      { w: '式神', k: 'しきがみ' }, { w: '古文書', k: 'こもんじょ' }, { w: '守護霊', k: 'しゅごれい' },
      { w: '陰陽師', k: 'おんみょうじ' }, { w: '結界術', k: 'けっかいじゅつ' }, { w: '悪魔祓い', k: 'あくまばらい' },
      { w: '天下無双', k: 'てんかむそう' }, { w: '魑魅魍魎', k: 'ちみもうりょう' },
      { w: '不倶戴天', k: 'ふぐたいてん' }, { w: '封印解除', k: 'ふういんかいじょ' },
      { w: '呪術返し', k: 'じゅじゅつがえし' }, { w: '生者必滅', k: 'しょうじゃひつめつ' },
      { w: '鬼', k: 'おに' }, { w: '龍', k: 'りゅう' }, { w: '蛇', k: 'へび' }, { w: '骸', k: 'むくろ' },
      { w: '棺', k: 'ひつぎ' }, { w: '墓標', k: 'ぼひょう' }, { w: '鎖', k: 'くさり' }, { w: '祭壇', k: 'さいだん' },
      { w: '護符', k: 'ごふ' }, { w: '呪符', k: 'じゅふ' }, { w: '香炉', k: 'こうろ' }, { w: '仮面', k: 'かめん' },
      { w: '幻影', k: 'げんえい' }, { w: '瘴気', k: 'しょうき' }, { w: '黒魔術', k: 'くろまじゅつ' },
      { w: '降霊術', k: 'こうれいじゅつ' }, { w: '錬金術', k: 'れんきんじゅつ' }, { w: '召喚陣', k: 'しょうかんじん' },
      { w: '魔女', k: 'まじょ' }, { w: '魔剣', k: 'まけん' }, { w: '聖水', k: 'せいすい' }, { w: '銀弾', k: 'ぎんだん' },
      { w: '黄泉路', k: 'よみじ' }, { w: '常闇', k: 'とこやみ' }, { w: '天啓', k: 'てんけい' },
      { w: '結界石', k: 'けっかいせき' }, { w: '封魔陣', k: 'ふうまじん' }, { w: '守護結界', k: 'しゅごけっかい' },
      { w: '悪逆非道', k: 'あくぎゃくひどう' }, { w: '傍若無人', k: 'ぼうじゃくぶじん' },
      { w: '魑魅魍魎跋扈', k: 'ちみもうりょうばっこ' }, { w: '大願成就', k: 'たいがんじょうじゅ' },
      { w: '不老不死', k: 'ふろうふし' }, { w: '輪廻転生', k: 'りんねてんしょう' },
    ],
    en: [
      'rune', 'omen', 'hex', 'relic', 'sigil', 'charm', 'spell', 'wraith', 'shrine', 'oracle',
      'blade', 'shield', 'quiver', 'bulwark', 'rampart', 'citadel', 'garrison', 'gauntlet',
      'phantom', 'revenant', 'banish', 'sever', 'kindle', 'fracture', 'silhouette',
      'labyrinthine', 'phantasmagoria', 'metamorphosis', 'unfathomable', 'irreversible',
      'talisman', 'grimoire', 'sorcerer', 'moonstone', 'sanctuary', 'wardstone', 'shadowveil',
      'blackthorn', 'nightshade', 'apparition', 'invocation', 'incantation', 'necromancer',
      'thaumaturgy', 'transfigure', 'necromantic', 'transmigration',
      'urn', 'pyre', 'bane', 'toll', 'veil', 'wisp', 'idol', 'curse', 'crypt', 'tomb',
      'coven', 'ghoul', 'lich', 'chant', 'shard', 'brand', 'thrall',
      'warlock', 'seance', 'effigy', 'reliquary', 'sepulchre', 'catacomb', 'obsidian',
      'malediction', 'benediction', 'summoning', 'banishment', 'consecrate',
      'soulbinding', 'hellfire', 'nightmare', 'witchcraft', 'blooddebt',
    ],
  },
  {
    id: 'memory',
    name: { en: 'THE MEMORY', ja: '記 憶' },
    hue: 35,
    shape: 'ring',
    motif: 'bokeh',
    ja: [
      { w: '手紙', k: 'てがみ' }, { w: '写真', k: 'しゃしん' }, { w: '記憶', k: 'きおく' }, { w: '希望', k: 'きぼう' },
      { w: '勇気', k: 'ゆうき' }, { w: '孤独', k: 'こどく' }, { w: '再会', k: 'さいかい' }, { w: '約束', k: 'やくそく' },
      { w: '恋愛', k: 'れんあい' }, { w: '深夜', k: 'しんや' }, { w: '旋律', k: 'せんりつ' }, { w: '和音', k: 'わおん' },
      { w: '拍子', k: 'ひょうし' }, { w: '独奏', k: 'どくそう' }, { w: '喧騒', k: 'けんそう' }, { w: '接吻', k: 'せっぷん' },
      { w: '新聞', k: 'しんぶん' }, { w: '雑誌', k: 'ざっし' }, { w: '学校', k: 'がっこう' }, { w: '教室', k: 'きょうしつ' },
      { w: '黒板', k: 'こくばん' }, { w: '宿題', k: 'しゅくだい' }, { w: '切符', k: 'きっぷ' }, { w: '旅行', k: 'りょこう' },
      { w: '出発', k: 'しゅっぱつ' }, { w: '到着', k: 'とうちゃく' }, { w: '今日は', k: 'こんにちは' },
      { w: '青春時代', k: 'せいしゅんじだい' }, { w: '有言実行', k: 'ゆうげんじっこう' }, { w: '感慨無量', k: 'かんがいむりょう' },
      { w: '思い出', k: 'おもいで' }, { w: '初恋', k: 'はつこい' }, { w: '故郷', k: 'ふるさと' },
      { w: '文化祭', k: 'ぶんかさい' }, { w: '思春期', k: 'ししゅんき' }, { w: '通学路', k: 'つうがくろ' },
      { w: '同窓会', k: 'どうそうかい' }, { w: '喜怒哀楽', k: 'きどあいらく' }, { w: '温故知新', k: 'おんこちしん' },
      { w: '幼馴染', k: 'おさななじみ' }, { w: '卒業式', k: 'そつぎょうしき' },
      { w: '記念写真', k: 'きねんしゃしん' }, { w: '完全無欠', k: 'かんぜんむけつ' },
      { w: '一生懸命', k: 'いっしょうけんめい' },
      { w: '面影', k: 'おもかげ' }, { w: '名残', k: 'なごり' }, { w: '余韻', k: 'よいん' }, { w: '郷愁', k: 'きょうしゅう' },
      { w: '未練', k: 'みれん' }, { w: '嘆息', k: 'たんそく' }, { w: '安堵', k: 'あんど' }, { w: '愛惜', k: 'あいせき' },
      { w: '日記', k: 'にっき' }, { w: '葉書', k: 'はがき' }, { w: '便箋', k: 'びんせん' }, { w: '栞', k: 'しおり' },
      { w: '文庫本', k: 'ぶんこぼん' }, { w: '古書店', k: 'こしょてん' }, { w: '喫茶店', k: 'きっさてん' },
      { w: '待合室', k: 'まちあいしつ' }, { w: '停留所', k: 'ていりゅうじょ' }, { w: '帰り道', k: 'かえりみち' },
      { w: '放課後', k: 'ほうかご' }, { w: '教科書', k: 'きょうかしょ' }, { w: '下駄箱', k: 'げたばこ' },
      { w: '運動会', k: 'うんどうかい' }, { w: '修学旅行', k: 'しゅうがくりょこう' }, { w: '合唱曲', k: 'がっしょうきょく' },
      { w: '子守唄', k: 'こもりうた' }, { w: '鎮魂歌', k: 'ちんこんか' }, { w: '追憶', k: 'ついおく' },
      { w: '別離', k: 'べつり' }, { w: '再訪', k: 'さいほう' }, { w: '約束の日', k: 'やくそくのひ' },
      { w: '十年後', k: 'じゅうねんご' }, { w: '有終の美', k: 'ゆうしゅうのび' }, { w: '光陰矢の如し', k: 'こういんやのごとし' },
      { w: '疎遠', k: 'そえん' }, { w: '無我夢中', k: 'むがむちゅう' },
    ],
    en: [
      'echo', 'vow', 'ache', 'dusk', 'letter', 'memory', 'promise', 'courage', 'longing', 'reunion',
      'silence', 'whisper', 'clamor', 'lullaby', 'requiem', 'cadence', 'refrain', 'solitude',
      'vertigo', 'nostalgia', 'threshold', 'corridor', 'unravel', 'relentless', 'unwavering',
      'crystallization', 'reverberation', 'extraordinary', 'unquestionable', 'incandescent',
      'farewell', 'yesterday', 'departure', 'heartache', 'lamplight', 'childhood', 'sentiment',
      'homecoming', 'aftertaste', 'wistfulness', 'remembrance', 'reminiscence',
      'keepsake', 'birthday', 'daybreak', 'homesick', 'suitcase', 'saltwind',
      'dear', 'note', 'kiss', 'wish', 'scar', 'hush', 'diary', 'album', 'ticket', 'ribbon',
      'candle', 'window', 'attic', 'garden', 'summer', 'winter', 'sunday', 'evening',
      'postcard', 'notebook', 'bookmark', 'classroom', 'hallway', 'stairwell', 'platform',
      'graduation', 'reflection', 'confession', 'afternoon', 'twilight', 'bittersweet',
      'handwriting', 'photograph', 'anniversary', 'recollection', 'sentimental',
      'unforgotten', 'yesteryear', 'daydreaming', 'lastsummer',
    ],
  },
];

/** 章あたりのウェーブ数。最後の 1 ウェーブがボス。 */
export const WAVES_PER_CHAPTER = 5;

export const chapterOf = (wave) =>
  CHAPTERS[(Math.ceil(wave / WAVES_PER_CHAPTER) - 1) % CHAPTERS.length];

export const isBossWave = (wave) => wave % WAVES_PER_CHAPTER === 0;
